# This rule is not used by the project atlasdb itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants read-only access to databases.atlasdb.io resources.
# This role is intended for users who need visibility into these resources
# without permissions to modify them. It is ideal for monitoring purposes and limited-access viewing.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: atlasdb
    app.kubernetes.io/managed-by: kustomize
  name: postgrescluster-viewer-role
rules:
- apiGroups:
  - databases.atlasdb.io
  resources:
  - postgresclusters
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - databases.atlasdb.io
  resources:
  - postgresclusters/status
  verbs:
  - get
